# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6a5a8022c96345c8d06fd05e4999af70681ab545190b5726888ded57ead0c65d7e8bac2ff8affead7a51db9e25f1b5ff374aa22e036d42946ac10372c2490ee

test:
  secret_key_base: 26d218e70f7563c05436bd128ea1ad5f3e5d890185c47c6439c52bdf1af3ddbe76c29b026339ada2b839c0306f7a84cbc13fca41ab078bf31f210e0ac2c4cdf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
